QUESTION_ANSWERS = {
    "experience": "6",
    "total experience": "6",
    "relevant experience": "6",
    "angular": "6",
    "angular development": "6",
    "bootstrap": "6",
    "javascript": "6",
    "typescript": "6",
    "current ctc": "2100000",
    "expected ctc": "3000000",
    "ctc": "3000000",
    "notice period": "15 Days",
    "serving notice": "No",
    "immediate joiner": "No",
    "available": "Yes",
    "virtual interview": "Yes",
    "willing to relocate": "Yes",
    "relocate": "Yes",
    "willing": "Yes",
    "join": "Yes",
    "walk-in": "Yes",
    "NP": "15 Days"
}